name: example_plugin
description: A new flutter plugin project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.5.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  universal_html: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.example_plugin
        pluginClass: ExamplePlugin
      ios:
        pluginClass: ExamplePlugin
      web:
        pluginClass: ExamplePlugin
        fileName: example_plugin_web.dart
